main:
  push:
    - imports: 
        - hhttps://cnb.cool/xiaofei/secrets/-/blob/main/github.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/lixiaofei123/toolbox_web.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}