version: '3.8'

services:
  base64-converter:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: base64-converter
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.base64-converter.rule=Host(`localhost`)"
      - "traefik.http.services.base64-converter.loadbalancer.server.port=80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
